name: Weekly App Execution

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch: 

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build and Run App - Jr
        run: |
          dotnet restore
          dotnet run m2 6 --project LotteryCrawler.App/LotteryCrawler.App.csproj --configuration Release > result_app_m2_jr.txt

      - name: Build and Run App - Mumu
        run: |
          dotnet restore
          dotnet run m2 6 --project LotteryCrawler.App/LotteryCrawler.App.csproj --configuration Release > result_app_m2_mumu.txt
              
      - name: Build and Run Study
        run: |
          dotnet restore
          dotnet run s --project LotteryCrawler.Study/LotteryCrawler.Study.csproj --configuration Release > result_study.txt

      - name: Send Email - Jr
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mailgun.org
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Apostas da mega sena - ${{ github.run_id }}"
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: "Serviço de automação <${{ secrets.SENDER_EMAIL }}>"
          body: "The weekly task has completed. Please find the log attached."
          attachments: result_app_m2_jr.txt,result_study.txt
    
      - name: Send Email - Mumu
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mailgun.org
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Apostas da mega sena - ${{ github.run_id }}"
          to: ${{ secrets.RECIPIENT_EMAIL_2 }}
          from: "Serviço de automação <${{ secrets.SENDER_EMAIL }}>"
          body: "A tarefa foi finalizada. Confira o arquivo em anexo."
          attachments: result_app_m2_mumu.txt